CREATE TABLE user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  first_name VARCHAR(60) NOT NULL,
  last_name VARCHAR(60),
  profile_picture_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SET SQL_SAFE_UPDATES = 0;

UPDATE `user` SET email = LOWER(TRIM(email));
UPDATE `user` SET username = TRIM(username);
UPDATE `user` SET created_at = NOW() WHERE created_at IS NULL;
UPDATE `user` SET updated_at = NOW() WHERE updated_at IS NULL;

ALTER TABLE `user` MODIFY `profile_picture_url` TEXT NULL;
ALTER TABLE `user` MODIFY `email` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL;
ALTER TABLE `user` MODIFY `username` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL;
ALTER TABLE `user` MODIFY `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `user` MODIFY `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `user` ADD COLUMN `last_seen_at` TIMESTAMP NULL;
ALTER TABLE `user` ADD COLUMN `last_login_at` TIMESTAMP NULL;
ALTER TABLE `user` ADD COLUMN `email_verified` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `user` ADD COLUMN `is_active` TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE `user` ADD COLUMN `about` VARCHAR(140) NULL;
ALTER TABLE `user` ADD COLUMN `password_updated_at` TIMESTAMP NULL;
ALTER TABLE `user` ADD COLUMN `deleted_at` TIMESTAMP NULL;

SET SQL_SAFE_UPDATES = 1;

CREATE TABLE chat (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100),
  is_group BOOLEAN NOT NULL,
  created_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  image_url varchar(255),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
  FOREIGN KEY (created_by) REFERENCES user(id)
);

CREATE TABLE message (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  chat_id BIGINT NOT NULL,
  sender_id BIGINT NOT NULL,
  content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chat_id) REFERENCES chat(id),
  FOREIGN KEY (sender_id) REFERENCES user(id)
);

CREATE TABLE chat_participant (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,

    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    role ENUM('ADMIN', 'MEMBER') NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_muted BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_chat FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,

    UNIQUE KEY uq_chat_user (chat_id, user_id)
);

CREATE TABLE contact (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  owner_id BIGINT NOT NULL,
  email VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255),
  created_at DATETIME,
  updated_at DATETIME,
  CONSTRAINT uk_contact_owner_email UNIQUE (owner_id, email),
  CONSTRAINT fk_contact_owner FOREIGN KEY (owner_id) REFERENCES user (id)
);

